#!/bin/bash

QNX_BACKUP_AND_RECOVERY_PATH=/opt/qnx_backup_and_recovery
BACKUP_ROOT=/backups/QNX
PATHS_LIST=${QNX_BACKUP_AND_RECOVERY_PATH}/paths.list
HOSTS_LIST=${QNX_BACKUP_AND_RECOVERY_PATH}/hosts.list

